# Streamlit Cloud Secrets Configuration
# Copy this to your Streamlit Cloud app settings -> Secrets tab

[google_drive]
client_id = "641133812410-phlnghc1fau2gjt3e7m73sm5ec7n0s6v.apps.googleusercontent.com"
client_secret = "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"
refresh_token = "YOUR_REFRESH_TOKEN_HERE"  # Get this by running get_tokens_simple.py
folder_id = "YOUR_FOLDER_ID_HERE"  # Create folder in Google Drive and get ID from URL

[whatsapp]
access_token = "YOUR_WHATSAPP_TOKEN"  # Optional - app works without this
phone_number_id = "YOUR_PHONE_NUMBER_ID"  # Optional

[app]
debug_mode = false
demo_mode = false
environment = "production"