# Streamlit Secrets Configuration for MauEyeCare
# Copy this file to .streamlit/secrets.toml and add your actual tokens

# Google Drive API Configuration
GOOGLE_DRIVE_TOKEN = "your_google_drive_access_token_here"
GOOGLE_CLIENT_ID = "your_google_client_id_here"
GOOGLE_CLIENT_SECRET = "your_google_client_secret_here"
GOOGLE_REFRESH_TOKEN = "your_google_refresh_token_here"

# WhatsApp Business API Configuration
WHATSAPP_ACCESS_TOKEN = "your_whatsapp_access_token_here"
WHATSAPP_PHONE_NUMBER_ID = "your_whatsapp_phone_number_id_here"

# Database Configuration (optional)
DATABASE_URL = "sqlite:///eyecare.db"

# Application Settings
DOCTOR_NAME = "Dr. Danish"
CLINIC_NAME = "MauEyeCare Optical Center"
CLINIC_PHONE = "+91 92356-47410"
CLINIC_EMAIL = "tech@maueyecare.com"